[2018-10-14 10:27:44,255] ERROR in app: Exception on /index [GET]
Traceback (most recent call last):
  File "/home/philippe/virtenvs/ponthe/lib/python3.6/site-packages/sqlalchemy/orm/base.py", line 379, in _entity_descriptor
    return getattr(entity, key)
AttributeError: type object 'File' has no attribute 'year'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/philippe/virtenvs/ponthe/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/philippe/virtenvs/ponthe/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/philippe/virtenvs/ponthe/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/philippe/virtenvs/ponthe/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/philippe/virtenvs/ponthe/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/philippe/virtenvs/ponthe/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/philippe/Personnal/ponthe.enpc.org/web/app/ponthe/private/views.py", line 58, in index
    return render_events_template('index.html', categories=Category.query.all())
  File "/home/philippe/Personnal/ponthe.enpc.org/web/app/ponthe/private/views.py", line 49, in render_events_template
    dict_events = { year: Event.query.filter(File.query.filter_by(year=year, event_id=Event.id).exists()).all() for year in Year.query.order_by(Year.value).all() }
  File "/home/philippe/Personnal/ponthe.enpc.org/web/app/ponthe/private/views.py", line 49, in <dictcomp>
    dict_events = { year: Event.query.filter(File.query.filter_by(year=year, event_id=Event.id).exists()).all() for year in Year.query.order_by(Year.value).all() }
  File "/home/philippe/virtenvs/ponthe/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 1689, in filter_by
    for key, value in kwargs.items()]
  File "/home/philippe/virtenvs/ponthe/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 1689, in <listcomp>
    for key, value in kwargs.items()]
  File "/home/philippe/virtenvs/ponthe/lib/python3.6/site-packages/sqlalchemy/orm/base.py", line 383, in _entity_descriptor
    (description, key)
sqlalchemy.exc.InvalidRequestError: Entity '<class 'ponthe.models.File'>' has no property 'year'
[2018-10-14 10:27:44,404] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/philippe/virtenvs/ponthe/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/philippe/virtenvs/ponthe/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/philippe/virtenvs/ponthe/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/philippe/virtenvs/ponthe/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/philippe/virtenvs/ponthe/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/philippe/virtenvs/ponthe/lib/python3.6/site-packages/sqlalchemy/orm/base.py", line 379, in _entity_descriptor
    return getattr(entity, key)
AttributeError: type object 'File' has no attribute 'year'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/philippe/virtenvs/ponthe/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/philippe/virtenvs/ponthe/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/philippe/virtenvs/ponthe/lib/python3.6/site-packages/flask/app.py", line 1713, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/philippe/virtenvs/ponthe/lib/python3.6/site-packages/flask/app.py", line 1644, in handle_http_exception
    return handler(e)
  File "/home/philippe/Personnal/ponthe.enpc.org/web/app/ponthe/views.py", line 32, in page_not_found
    return render_events_template('404.html'), 404
  File "/home/philippe/Personnal/ponthe.enpc.org/web/app/ponthe/private/views.py", line 49, in render_events_template
    dict_events = { year: Event.query.filter(File.query.filter_by(year=year, event_id=Event.id).exists()).all() for year in Year.query.order_by(Year.value).all() }
  File "/home/philippe/Personnal/ponthe.enpc.org/web/app/ponthe/private/views.py", line 49, in <dictcomp>
    dict_events = { year: Event.query.filter(File.query.filter_by(year=year, event_id=Event.id).exists()).all() for year in Year.query.order_by(Year.value).all() }
  File "/home/philippe/virtenvs/ponthe/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 1689, in filter_by
    for key, value in kwargs.items()]
  File "/home/philippe/virtenvs/ponthe/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 1689, in <listcomp>
    for key, value in kwargs.items()]
  File "/home/philippe/virtenvs/ponthe/lib/python3.6/site-packages/sqlalchemy/orm/base.py", line 383, in _entity_descriptor
    (description, key)
sqlalchemy.exc.InvalidRequestError: Entity '<class 'ponthe.models.File'>' has no property 'year'
[2018-10-14 10:42:40,848] WARNING in _internal:  * Debugger is active!
[2018-10-14 10:44:32,424] WARNING in _internal:  * Debugger is active!
[2018-10-14 10:44:54,264] WARNING in _internal:  * Debugger is active!
[2018-10-14 11:06:44,070] WARNING in _internal:  * Debugger is active!
[2018-10-14 15:05:15,990] WARNING in _internal:  * Debugger is active!
[2018-10-14 15:15:01,189] WARNING in _internal:  * Debugger is active!
[2018-10-14 15:17:14,992] WARNING in _internal:  * Debugger is active!
[2018-10-14 15:33:51,550] WARNING in _internal:  * Debugger is active!
[2018-10-14 15:37:18,148] WARNING in _internal:  * Debugger is active!
[2018-10-14 15:46:09,411] WARNING in _internal:  * Debugger is active!
[2018-10-14 16:29:15,664] WARNING in _internal:  * Debugger is active!
[2018-10-14 16:34:05,019] WARNING in _internal:  * Debugger is active!
[2018-10-14 16:34:35,320] WARNING in _internal:  * Debugger is active!
[2018-10-14 16:35:51,268] WARNING in _internal:  * Debugger is active!
[2018-10-14 16:37:11,051] WARNING in _internal:  * Debugger is active!
[2018-10-14 16:38:03,717] WARNING in _internal:  * Debugger is active!
[2018-10-14 22:01:47,831] WARNING in _internal:  * Debugger is active!
[2018-10-14 22:09:31,838] WARNING in _internal:  * Debugger is active!
[2018-10-14 22:09:51,906] WARNING in _internal:  * Debugger is active!
[2018-10-14 22:10:12,921] WARNING in _internal:  * Debugger is active!
[2018-10-14 22:11:13,429] WARNING in _internal:  * Debugger is active!
[2018-10-14 22:12:35,629] WARNING in _internal:  * Debugger is active!
[2018-10-14 22:12:48,375] WARNING in _internal:  * Debugger is active!
[2018-10-14 22:16:06,151] WARNING in _internal:  * Debugger is active!
[2018-10-14 22:17:28,134] WARNING in _internal:  * Debugger is active!
[2018-10-14 22:19:39,842] WARNING in _internal:  * Debugger is active!
[2018-10-14 22:19:54,680] WARNING in _internal:  * Debugger is active!
[2018-10-14 22:20:00,285] WARNING in _internal:  * Debugger is active!
[2018-10-14 22:20:03,110] WARNING in _internal:  * Debugger is active!
[2018-10-14 22:20:25,920] WARNING in _internal:  * Debugger is active!
[2018-10-14 22:21:30,589] WARNING in _internal:  * Debugger is active!
[2018-10-14 22:21:46,530] WARNING in _internal:  * Debugger is active!
[2018-10-14 22:22:13,716] WARNING in _internal:  * Debugger is active!
[2018-10-14 22:23:28,901] WARNING in _internal:  * Debugger is active!
[2018-10-14 22:25:32,075] WARNING in _internal:  * Debugger is active!
[2018-10-14 22:27:44,179] WARNING in _internal:  * Debugger is active!
[2018-10-14 22:27:51,737] WARNING in _internal:  * Debugger is active!
[2018-10-14 22:27:57,262] WARNING in _internal:  * Debugger is active!
[2018-10-14 22:54:24,589] WARNING in _internal:  * Debugger is active!
[2018-10-14 22:56:22,495] WARNING in _internal:  * Debugger is active!
[2018-10-14 22:56:57,464] WARNING in _internal:  * Debugger is active!
[2018-10-14 23:01:10,237] WARNING in _internal:  * Debugger is active!
[2018-10-14 23:04:04,709] WARNING in _internal:  * Debugger is active!
[2018-10-14 23:05:23,700] WARNING in _internal:  * Debugger is active!
[2018-10-14 23:05:58,282] WARNING in _internal:  * Debugger is active!
[2018-10-14 23:06:50,773] WARNING in _internal:  * Debugger is active!
[2018-10-14 23:28:44,233] WARNING in _internal:  * Debugger is active!
[2018-10-14 23:32:10,243] WARNING in _internal:  * Debugger is active!
[2018-10-14 23:32:26,002] WARNING in _internal:  * Debugger is active!
[2018-10-14 23:33:29,579] WARNING in _internal:  * Debugger is active!
[2018-10-14 23:34:12,719] WARNING in _internal:  * Debugger is active!
[2018-10-14 23:39:30,224] WARNING in _internal:  * Debugger is active!
[2018-10-14 23:45:37,997] WARNING in _internal:  * Debugger is active!
[2018-10-14 23:49:25,377] WARNING in _internal:  * Debugger is active!
[2018-10-14 23:50:32,193] WARNING in _internal:  * Debugger is active!
[2018-10-14 23:50:54,249] WARNING in _internal:  * Debugger is active!
[2018-10-14 23:54:53,791] WARNING in _internal:  * Debugger is active!
[2018-10-14 23:55:26,829] WARNING in _internal:  * Debugger is active!
[2018-10-14 23:57:17,143] WARNING in _internal:  * Debugger is active!
[2018-10-14 23:58:10,561] WARNING in _internal:  * Debugger is active!
[2018-10-14 23:58:20,121] WARNING in _internal:  * Debugger is active!
[2018-10-14 23:59:09,408] WARNING in _internal:  * Debugger is active!
